GET http://localhost:3000/api/v1/users?pageSize=2&pageNum=2
Accept: application/json

###
PUT http://localhost:3000/api/v1/user/5
Content-Type: application/json

{
  "username": "yudi5",
  "role": 5
}

###
DELETE http://localhost:3000/api/v1/user/5
Content-Type: application/json


###
POST http://localhost:3000/api/v1/user/add
Content-Type: application/json

{
  "username": "yudi5",
  "password": "yudi5",
  "role": 0
}

###
