GET http://localhost:3000/api/v1/users?pageSize=2&pageNum=2
Accept: application/json

###
PUT http://localhost:3000/api/v1/user/5
Content-Type: application/json

{
  "username": "yudi5",
  "role": 5
}

###
DELETE http://localhost:3000/api/v1/user/5
Content-Type: application/json


###
POST http://localhost:3000/api/v1/user/add
Content-Type: application/json

{
  "username": "yudi5",
  "password": "yudi5",
  "role": 0
}

###
GET http://localhost:3000/api/v1/categories?pageSize=2&pageNum=2
Accept: application/json

###
PUT http://localhost:3000/api/v1/category/3
Content-Type: application/json

{
  "name": "golang"
}

###
DELETE http://localhost:3000/api/v1/category/3
Content-Type: application/json


###
POST http://localhost:3000/api/v1/category/add
Content-Type: application/json

{
  "name": "golang"
}

###

GET http://localhost:3000/api/v1/article/list/1?pageSize=3&pageNum=1
Accept: application/json

###


GET http://localhost:3000/api/v1/article/info/3
Accept: application/json

###


GET http://localhost:3000/api/v1/articles?pageSize=3&pageNum=1
Accept: application/json

###
PUT http://localhost:3000/api/v1/article/1
Content-Type: application/json

{
  "title": "Test Article666",
  "cid": 2,
  "desc": "Test Article Description666",
  "content": "Test Article Content666",
  "img": "Test Article Image666"
}

###


DELETE http://localhost:3000/api/v1/article/100
Content-Type: application/json

###

POST http://localhost:3000/api/v1/article/add
Content-Type: application/json

{
  "title": "Vue1",
  "cid": 3,
  "desc": "Vue1",
  "content": "Vue1",
  "img": "Vue1"
}

###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "username": "yudi5",
  "password": "yudi5 "
}
